image: node:latest

stages:
  - build
  - test
  - analyse

run-build:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules

run-test:
  stage: test
  script:
    - npm run test
  artifacts:
    paths:
      - node_modules/

run-analyse:
  stage: analyse
  script:
    - npm run lint
